/*
 * AMRIT – Accessible Medical Records via Integrated Technologies
 * Integrated EHR (Electronic Health Records) Solution
 *
 * Copyright (C) "Piramal Swasthya Management and Research Institute"
 *
 * This file is part of AMRIT.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */

// Production environment. Real production hosts and the encryption key are injected at
// build time from environment.ci.ts (generated by CI from environment.ci.ts.template).
// These values are intentionally left blank so a misconfigured production build fails
// fast instead of silently routing live traffic to dev/UAT. Never commit real secrets here.
const sessionStorageEncKey = '';
const commonAPI = '';
const adminAPI = '';
const API1097 = '';
const telephoneServer = '';
const siteKey = '';
const captchaChallengeURL = '';
const enableCaptcha = false;

// Fail fast: a production bundle must never boot with blank core config. If CI has not
// injected real values (see environment.ci.ts.template), throw at module evaluation
// rather than silently routing live traffic to the wrong/empty backend.
const requiredProdConfig: Record<string, string> = {
  sessionStorageEncKey,
  commonAPI,
  adminAPI,
  API1097,
};
for (const [key, value] of Object.entries(requiredProdConfig)) {
  if (!value.trim()) {
    throw new Error(`[environment.prod] Missing required production config: ${key}`);
  }
}

export const environment = {
  production: true,
  invalidCallType: 'Invalid',
  encKey: sessionStorageEncKey,
  commonAPI,
  ip1097: API1097,
  adminAPI,
  telephoneServer,
  siteKey,
  captchaChallengeURL,
  enableCaptcha,
  useApimanKey: true,
  sessionTimeoutMinutes: 27,
};
